# preload = /path/to/image.png
preload = /home/dallas/.config/hypr/walls/1.png
preload = /home/dallas/.config/hypr/walls/2.png
preload = /home/dallas/.config/hypr/walls/3.png
preload = /home/dallas/.config/hypr/walls/4.png
preload = /home/dallas/.config/hypr/walls/5.png
preload = /home/dallas/.config/hypr/walls/6.png
preload = /home/dallas/.config/hypr/walls/7.png
preload = /home/dallas/.config/hypr/walls/8.png
preload = /home/dallas/.config/hypr/walls/9.png
preload = /home/dallas/.config/hypr/walls/0.png

# if more than one preload is desired then continue to preload other backgrounds
# preload = /path/to/next_image.png
# .. more preloads

# set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
# wallpaper = monitor1,/path/to/image.png
# wallpaper = monitor,~/Pictures/Wallpapers/GirlCatRoof.png
wallpaper = DP-2,/home/dallas/.config/hypr/walls/1.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/2.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/3.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/4.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/5.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/6.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/7.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/8.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/9.png
#wallpaper = DP-2,/home/dallas/.config/hypr/walls/0.png

# if more than one monitor in use, can load a 2nd image
# wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
